import { Keyboard, KeyboardLayoutKey } from "../types";
export const qwertySplit36key: Keyboard = {
    homeRow: ['10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',],
    keys: [
        { id: '0', w: 1, h: 1, x: 0, y: 0, key: { code: "q", also: ["Q"] } },
        { id: '1', w: 1, h: 1, x: 1, y: 0, key: { code: "w", also: ["W"] } },
        { id: '2', w: 1, h: 1, x: 2, y: 0, key: { code: "e", also: ["E"] } },
        { id: '3', w: 1, h: 1, x: 3, y: 0, key: { code: "r", also: ["R"] } },
        { id: '4', w: 1, h: 1, x: 4, y: 0, key: { code: "t", also: ["T"] } },
        { id: '5', w: 1, h: 1, x: 6, y: 0, key: { code: "y", also: ["Y"] } },
        { id: '6', w: 1, h: 1, x: 7, y: 0, key: { code: "u", also: ["U"] } },
        { id: '7', w: 1, h: 1, x: 8, y: 0, key: { code: "i", also: ["I"] } },
        { id: '8', w: 1, h: 1, x: 9, y: 0, key: { code: "o", also: ["O"] } },
        { id: '9', w: 1, h: 1, x: 10, y: 0, key: { code: "p", also: ["P"] } },

        { id: '10', w: 1, h: 1, x: 0, y: 1, key: { code: "a", also: ["A"] } },
        { id: '11', w: 1, h: 1, x: 1, y: 1, key: { code: "s", also: ["S"] } },
        { id: '12', w: 1, h: 1, x: 2, y: 1, key: { code: "d", also: ["D"] } },
        { id: '13', w: 1, h: 1, x: 3, y: 1, key: { code: "f", also: ["F"] } },
        { id: '14', w: 1, h: 1, x: 4, y: 1, key: { code: "g", also: ["G"] } },
        { id: '15', w: 1, h: 1, x: 6, y: 1, key: { code: "h", also: ["H"] } },
        { id: '16', w: 1, h: 1, x: 7, y: 1, key: { code: "j", also: ["J"] } },
        { id: '17', w: 1, h: 1, x: 8, y: 1, key: { code: "k", also: ["K"] } },
        { id: '18', w: 1, h: 1, x: 9, y: 1, key: { code: "l", also: ["L"] } },
        { id: '19', w: 1, h: 1, x: 10, y: 1, key: { code: ";", also: [":"] } },

        { id: '20', w: 1, h: 1, x: 0, y: 2, key: { code: "z", also: ["Z"] } },
        { id: '21', w: 1, h: 1, x: 1, y: 2, key: { code: "x", also: ["X"] } },
        { id: '22', w: 1, h: 1, x: 2, y: 2, key: { code: "c", also: ["C"] } },
        { id: '23', w: 1, h: 1, x: 3, y: 2, key: { code: "v", also: ["V"] } },
        { id: '24', w: 1, h: 1, x: 4, y: 2, key: { code: "b", also: ["B"] } },
        { id: '25', w: 1, h: 1, x: 6, y: 2, key: { code: "n", also: ["N"] } },
        { id: '26', w: 1, h: 1, x: 7, y: 2, key: { code: "m", also: ["M"] } },
        { id: '27', w: 1, h: 1, x: 8, y: 2, key: { code: ",", also: ["<"] } },
        { id: '28', w: 1, h: 1, x: 9, y: 2, key: { code: ".", also: [">"] } },
        { id: '29', w: 1, h: 1, x: 10, y: 2, key: { code: "/", also: ["?"] } },

        { id: '30', w: 1, h: 1, x: 2.25, y: 3.25, key: { code: "L1", also: [] } },
        { id: '31', w: 1, h: 1, x: 3.25, y: 3.25, key: { code: "ctrl", also: [] } },
        { id: '32', w: 1, h: 1, x: 4.25, y: 3.25, key: { code: "ent", also: ["L2"] } },

        { id: '33', w: 1, h: 1, x: 5.75, y: 3.25, key: { code: "leader", also: [] } },
        { id: '34', w: 1, h: 1, x: 6.75, y: 3.25, key: { code: "spc", also: ["L1"] } },
        { id: '35', w: 1, h: 1, x: 7.75, y: 3.25, key: { code: "NO", also: [] } },

    ]
};
export const colemakSplit36key: Keyboard = {
    homeRow: ['10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',],
    keys: [
        { id: '0', w: 1, h: 1, x: 0, y: 0, key: { code: "q", also: ["Q"] } },
        { id: '1', w: 1, h: 1, x: 1, y: 0, key: { code: "w", also: ["W"] } },
        { id: '2', w: 1, h: 1, x: 2, y: 0, key: { code: "f", also: ["F"] } },
        { id: '3', w: 1, h: 1, x: 3, y: 0, key: { code: "p", also: ["P"] } },
        { id: '4', w: 1, h: 1, x: 4, y: 0, key: { code: "g", also: ["G"] } },
        { id: '5', w: 1, h: 1, x: 6, y: 0, key: { code: "j", also: ["J"] } },
        { id: '6', w: 1, h: 1, x: 7, y: 0, key: { code: "l", also: ["L"] } },
        { id: '7', w: 1, h: 1, x: 8, y: 0, key: { code: "u", also: ["U"] } },
        { id: '8', w: 1, h: 1, x: 9, y: 0, key: { code: "y", also: ["Y"] } },
        { id: '9', w: 1, h: 1, x: 10, y: 0, key: { code: ";", also: [":"] } },

        { id: '10', w: 1, h: 1, x: 0, y: 1, key: { code: "a", also: ["A"] } },
        { id: '11', w: 1, h: 1, x: 1, y: 1, key: { code: "r", also: ["R"] } },
        { id: '12', w: 1, h: 1, x: 2, y: 1, key: { code: "s", also: ["S"] } },
        { id: '13', w: 1, h: 1, x: 3, y: 1, key: { code: "t", also: ["T"] } },
        { id: '14', w: 1, h: 1, x: 4, y: 1, key: { code: "d", also: ["D"] } },
        { id: '15', w: 1, h: 1, x: 6, y: 1, key: { code: "h", also: ["H"] } },
        { id: '16', w: 1, h: 1, x: 7, y: 1, key: { code: "n", also: ["N"] } },
        { id: '17', w: 1, h: 1, x: 8, y: 1, key: { code: "e", also: ["E"] } },
        { id: '18', w: 1, h: 1, x: 9, y: 1, key: { code: "i", also: ["I"] } },
        { id: '19', w: 1, h: 1, x: 10, y: 1, key: { code: "o", also: ["O"] } },

        { id: '20', w: 1, h: 1, x: 0, y: 2, key: { code: "z", also: ["Z"] } },
        { id: '21', w: 1, h: 1, x: 1, y: 2, key: { code: "x", also: ["X"] } },
        { id: '22', w: 1, h: 1, x: 2, y: 2, key: { code: "c", also: ["C"] } },
        { id: '23', w: 1, h: 1, x: 3, y: 2, key: { code: "v", also: ["V"] } },
        { id: '24', w: 1, h: 1, x: 4, y: 2, key: { code: "b", also: ["B"] } },
        { id: '25', w: 1, h: 1, x: 6, y: 2, key: { code: "k", also: ["K"] } },
        { id: '26', w: 1, h: 1, x: 7, y: 2, key: { code: "m", also: ["M"] } },
        { id: '27', w: 1, h: 1, x: 8, y: 2, key: { code: ",", also: ["<"] } },
        { id: '28', w: 1, h: 1, x: 9, y: 2, key: { code: ".", also: [">"] } },
        { id: '29', w: 1, h: 1, x: 10, y: 2, key: { code: "/", also: ["?"] } },

        { id: '30', w: 1, h: 1, x: 2.25, y: 3.25, key: { code: "L1", also: [] } },
        { id: '31', w: 1, h: 1, x: 3.25, y: 3.25, key: { code: "ctrl", also: [] } },
        { id: '32', w: 1, h: 1, x: 4.25, y: 3.25, key: { code: "ent", also: ["L2"] } },

        { id: '33', w: 1, h: 1, x: 5.75, y: 3.25, key: { code: "leader", also: [] } },
        { id: '34', w: 1, h: 1, x: 6.75, y: 3.25, key: { code: "spc", also: ["L1"] } },
        { id: '35', w: 1, h: 1, x: 7.75, y: 3.25, key: { code: "NO", also: [] } },
    ]
}

export const dvorakSplit36key: Keyboard = {
    homeRow: ['10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',],
    keys: [
        { id: '0', w: 1, h: 1, x: 0, y: 0, key: { code: "'", also: ["\""] } },
        { id: '1', w: 1, h: 1, x: 1, y: 0, key: { code: ",", also: ["<"] } },
        { id: '2', w: 1, h: 1, x: 2, y: 0, key: { code: ".", also: [">"] } },
        { id: '3', w: 1, h: 1, x: 3, y: 0, key: { code: "p", also: ["P"] } },
        { id: '4', w: 1, h: 1, x: 4, y: 0, key: { code: "y", also: ["Y"] } },
        { id: '5', w: 1, h: 1, x: 6, y: 0, key: { code: "f", also: ["F"] } },
        { id: '6', w: 1, h: 1, x: 7, y: 0, key: { code: "g", also: ["G"] } },
        { id: '7', w: 1, h: 1, x: 8, y: 0, key: { code: "c", also: ["C"] } },
        { id: '8', w: 1, h: 1, x: 9, y: 0, key: { code: "r", also: ["R"] } },
        { id: '9', w: 1, h: 1, x: 10, y: 0, key: { code: "l", also: ["L"] } },

        { id: '10', w: 1, h: 1, x: 0, y: 1, key: { code: "a", also: ["A"] } },
        { id: '11', w: 1, h: 1, x: 1, y: 1, key: { code: "o", also: ["O"] } },
        { id: '12', w: 1, h: 1, x: 2, y: 1, key: { code: "e", also: ["E"] } },
        { id: '13', w: 1, h: 1, x: 3, y: 1, key: { code: "u", also: ["U"] } },
        { id: '14', w: 1, h: 1, x: 4, y: 1, key: { code: "i", also: ["I"] } },
        { id: '15', w: 1, h: 1, x: 6, y: 1, key: { code: "d", also: ["D"] } },
        { id: '16', w: 1, h: 1, x: 7, y: 1, key: { code: "h", also: ["H"] } },
        { id: '17', w: 1, h: 1, x: 8, y: 1, key: { code: "t", also: ["T"] } },
        { id: '18', w: 1, h: 1, x: 9, y: 1, key: { code: "n", also: ["N"] } },
        { id: '19', w: 1, h: 1, x: 10, y: 1, key: { code: "s", also: ["S"] } },

        { id: '20', w: 1, h: 1, x: 0, y: 2, key: { code: ";", also: [":"] } },
        { id: '21', w: 1, h: 1, x: 1, y: 2, key: { code: "q", also: ["Q"] } },
        { id: '22', w: 1, h: 1, x: 2, y: 2, key: { code: "j", also: ["J"] } },
        { id: '23', w: 1, h: 1, x: 3, y: 2, key: { code: "k", also: ["K"] } },
        { id: '24', w: 1, h: 1, x: 4, y: 2, key: { code: "x", also: ["X"] } },
        { id: '25', w: 1, h: 1, x: 6, y: 2, key: { code: "b", also: ["B"] } },
        { id: '26', w: 1, h: 1, x: 7, y: 2, key: { code: "m", also: ["M"] } },
        { id: '27', w: 1, h: 1, x: 8, y: 2, key: { code: "w", also: ["W"] } },
        { id: '28', w: 1, h: 1, x: 9, y: 2, key: { code: "v", also: ["V"] } },
        { id: '29', w: 1, h: 1, x: 10, y: 2, key: { code: "z", also: ["Z"] } },

        { id: '30', w: 1, h: 1, x: 2.25, y: 3.25, key: { code: "L1", also: [] } },
        { id: '31', w: 1, h: 1, x: 3.25, y: 3.25, key: { code: "ctrl", also: [] } },
        { id: '32', w: 1, h: 1, x: 4.25, y: 3.25, key: { code: "ent", also: ["L2"] } },

        { id: '33', w: 1, h: 1, x: 5.75, y: 3.25, key: { code: "leader", also: [] } },
        { id: '34', w: 1, h: 1, x: 6.75, y: 3.25, key: { code: "spc", also: ["L1"] } },
        { id: '35', w: 1, h: 1, x: 7.75, y: 3.25, key: { code: "NO", also: [] } },
    ]
}
export const workmanSplit36key: Keyboard = {
    homeRow: ['10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',],
    keys: [
        { id: '0', w: 1, h: 1, x: 0, y: 0, key: { code: "'", also: ["\""] } },
        { id: '1', w: 1, h: 1, x: 1, y: 0, key: { code: ",", also: ["<"] } },
        { id: '2', w: 1, h: 1, x: 2, y: 0, key: { code: ".", also: [">"] } },
        { id: '3', w: 1, h: 1, x: 3, y: 0, key: { code: "p", also: ["P"] } },
        { id: '4', w: 1, h: 1, x: 4, y: 0, key: { code: "y", also: ["Y"] } },
        { id: '5', w: 1, h: 1, x: 6, y: 0, key: { code: "f", also: ["F"] } },
        { id: '6', w: 1, h: 1, x: 7, y: 0, key: { code: "g", also: ["G"] } },
        { id: '7', w: 1, h: 1, x: 8, y: 0, key: { code: "c", also: ["C"] } },
        { id: '8', w: 1, h: 1, x: 9, y: 0, key: { code: "r", also: ["R"] } },
        { id: '9', w: 1, h: 1, x: 10, y: 0, key: { code: "l", also: ["L"] } },

        { id: '10', w: 1, h: 1, x: 0, y: 1, key: { code: "a", also: ["A"] } },
        { id: '11', w: 1, h: 1, x: 1, y: 1, key: { code: "o", also: ["O"] } },
        { id: '12', w: 1, h: 1, x: 2, y: 1, key: { code: "e", also: ["E"] } },
        { id: '13', w: 1, h: 1, x: 3, y: 1, key: { code: "u", also: ["U"] } },
        { id: '14', w: 1, h: 1, x: 4, y: 1, key: { code: "i", also: ["I"] } },
        { id: '15', w: 1, h: 1, x: 6, y: 1, key: { code: "d", also: ["D"] } },
        { id: '16', w: 1, h: 1, x: 7, y: 1, key: { code: "h", also: ["H"] } },
        { id: '17', w: 1, h: 1, x: 8, y: 1, key: { code: "t", also: ["T"] } },
        { id: '18', w: 1, h: 1, x: 9, y: 1, key: { code: "n", also: ["N"] } },
        { id: '19', w: 1, h: 1, x: 10, y: 1, key: { code: "s", also: ["S"] } },

        { id: '20', w: 1, h: 1, x: 0, y: 2, key: { code: ";", also: [":"] } },
        { id: '21', w: 1, h: 1, x: 1, y: 2, key: { code: "q", also: ["Q"] } },
        { id: '22', w: 1, h: 1, x: 2, y: 2, key: { code: "j", also: ["J"] } },
        { id: '23', w: 1, h: 1, x: 3, y: 2, key: { code: "k", also: ["K"] } },
        { id: '24', w: 1, h: 1, x: 4, y: 2, key: { code: "x", also: ["X"] } },
        { id: '25', w: 1, h: 1, x: 6, y: 2, key: { code: "b", also: ["B"] } },
        { id: '26', w: 1, h: 1, x: 7, y: 2, key: { code: "m", also: ["M"] } },
        { id: '27', w: 1, h: 1, x: 8, y: 2, key: { code: "w", also: ["W"] } },
        { id: '28', w: 1, h: 1, x: 9, y: 2, key: { code: "v", also: ["V"] } },
        { id: '29', w: 1, h: 1, x: 10, y: 2, key: { code: "z", also: ["Z"] } },

        { id: '30', w: 1, h: 1, x: 2.25, y: 3.25, key: { code: "L1", also: [] } },
        { id: '31', w: 1, h: 1, x: 3.25, y: 3.25, key: { code: "ctrl", also: [] } },
        { id: '32', w: 1, h: 1, x: 4.25, y: 3.25, key: { code: "ent", also: ["L2"] } },

        { id: '33', w: 1, h: 1, x: 5.75, y: 3.25, key: { code: "leader", also: [] } },
        { id: '34', w: 1, h: 1, x: 6.75, y: 3.25, key: { code: "spc", also: ["L1"] } },
        { id: '35', w: 1, h: 1, x: 7.75, y: 3.25, key: { code: "NO", also: [] } },
    ]
}

export const handsdownSplit36key: Keyboard = {
    homeRow: ['10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',],
    keys: [
        { id: '0', w: 1, h: 1, x: 0, y: 0, key: { code: "q", also: ["Q"] } },
        { id: '1', w: 1, h: 1, x: 1, y: 0, key: { code: "w", also: ["W"] } },
        { id: '2', w: 1, h: 1, x: 2, y: 0, key: { code: "e", also: ["E"] } },
        { id: '3', w: 1, h: 1, x: 3, y: 0, key: { code: "r", also: ["R"] } },
        { id: '4', w: 1, h: 1, x: 4, y: 0, key: { code: "t", also: ["T"] } },
        { id: '5', w: 1, h: 1, x: 6, y: 0, key: { code: "y", also: ["Y"] } },
        { id: '6', w: 1, h: 1, x: 7, y: 0, key: { code: "u", also: ["U"] } },
        { id: '7', w: 1, h: 1, x: 8, y: 0, key: { code: "i", also: ["I"] } },
        { id: '8', w: 1, h: 1, x: 9, y: 0, key: { code: "o", also: ["O"] } },
        { id: '9', w: 1, h: 1, x: 10, y: 0, key: { code: "p", also: ["P"] } },

        { id: '10', w: 1, h: 1, x: 0, y: 1, key: { code: "a", also: ["A"] } },
        { id: '11', w: 1, h: 1, x: 1, y: 1, key: { code: "s", also: ["S"] } },
        { id: '12', w: 1, h: 1, x: 2, y: 1, key: { code: "d", also: ["D"] } },
        { id: '13', w: 1, h: 1, x: 3, y: 1, key: { code: "f", also: ["F"] } },
        { id: '14', w: 1, h: 1, x: 4, y: 1, key: { code: "g", also: ["G"] } },
        { id: '15', w: 1, h: 1, x: 6, y: 1, key: { code: "h", also: ["H"] } },
        { id: '16', w: 1, h: 1, x: 7, y: 1, key: { code: "j", also: ["J"] } },
        { id: '17', w: 1, h: 1, x: 8, y: 1, key: { code: "k", also: ["K"] } },
        { id: '18', w: 1, h: 1, x: 9, y: 1, key: { code: "l", also: ["L"] } },
        { id: '19', w: 1, h: 1, x: 10, y: 1, key: { code: ";", also: [":"] } },

        { id: '20', w: 1, h: 1, x: 0, y: 2, key: { code: "z", also: ["Z"] } },
        { id: '21', w: 1, h: 1, x: 1, y: 2, key: { code: "x", also: ["X"] } },
        { id: '22', w: 1, h: 1, x: 2, y: 2, key: { code: "c", also: ["C"] } },
        { id: '23', w: 1, h: 1, x: 3, y: 2, key: { code: "v", also: ["V"] } },
        { id: '24', w: 1, h: 1, x: 4, y: 2, key: { code: "b", also: ["B"] } },
        { id: '25', w: 1, h: 1, x: 6, y: 2, key: { code: "n", also: ["N"] } },
        { id: '26', w: 1, h: 1, x: 7, y: 2, key: { code: "m", also: ["M"] } },
        { id: '27', w: 1, h: 1, x: 8, y: 2, key: { code: ",", also: ["<"] } },
        { id: '28', w: 1, h: 1, x: 9, y: 2, key: { code: ".", also: [">"] } },
        { id: '29', w: 1, h: 1, x: 10, y: 2, key: { code: "/", also: ["?"] } },

        { id: '30', w: 1, h: 1, x: 2.25, y: 3.25, key: { code: "L1", also: [] } },
        { id: '31', w: 1, h: 1, x: 3.25, y: 3.25, key: { code: "ctrl", also: [] } },
        { id: '32', w: 1, h: 1, x: 4.25, y: 3.25, key: { code: "ent", also: ["L2"] } },

        { id: '33', w: 1, h: 1, x: 5.75, y: 3.25, key: { code: "leader", also: [] } },
        { id: '34', w: 1, h: 1, x: 6.75, y: 3.25, key: { code: "spc", also: ["L1"] } },
        { id: '35', w: 1, h: 1, x: 7.75, y: 3.25, key: { code: "NO", also: [] } },
    ]
}


export const qwertySplit42key: Keyboard = {
    homeRow: ['10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',],
    keys: [
        // Row 0
        { id: '-1', w: 1, h: 1, x: 0, y: 0, key: { code: "esc", also: [] } },
        { id: '0', w: 1, h: 1, x: 1, y: 0, key: { code: "q", also: ["Q"] } },
        { id: '1', w: 1, h: 1, x: 2, y: 0, key: { code: "w", also: ["W"] } },
        { id: '2', w: 1, h: 1, x: 3, y: 0, key: { code: "e", also: ["E"] } },
        { id: '3', w: 1, h: 1, x: 4, y: 0, key: { code: "r", also: ["R"] } },
        { id: '4', w: 1, h: 1, x: 5, y: 0, key: { code: "t", also: ["T"] } },
        { id: '5', w: 1, h: 1, x: 7, y: 0, key: { code: "y", also: ["Y"] } },
        { id: '6', w: 1, h: 1, x: 8, y: 0, key: { code: "u", also: ["U"] } },
        { id: '7', w: 1, h: 1, x: 9, y: 0, key: { code: "i", also: ["I"] } },
        { id: '8', w: 1, h: 1, x: 10, y: 0, key: { code: "o", also: ["O"] } },
        { id: '9', w: 1, h: 1, x: 11, y: 0, key: { code: "p", also: ["P"] } },
        { id: '10', w: 1, h: 1, x: 12, y: 0, key: { code: "Bksp", also: [] } },

        // Row 1
        { id: '11', w: 1, h: 1, x: 0, y: 1, key: { code: "ctrl", also: [] } },
        { id: '12', w: 1, h: 1, x: 1, y: 1, key: { code: "a", also: ["A"] } },
        { id: '13', w: 1, h: 1, x: 2, y: 1, key: { code: "s", also: ["S"] } },
        { id: '14', w: 1, h: 1, x: 3, y: 1, key: { code: "d", also: ["D"] } },
        { id: '15', w: 1, h: 1, x: 4, y: 1, key: { code: "f", also: ["F"] } },
        { id: '16', w: 1, h: 1, x: 5, y: 1, key: { code: "g", also: ["G"] } },
        { id: '17', w: 1, h: 1, x: 7, y: 1, key: { code: "h", also: ["H"] } },
        { id: '18', w: 1, h: 1, x: 8, y: 1, key: { code: "j", also: ["J"] } },
        { id: '19', w: 1, h: 1, x: 9, y: 1, key: { code: "k", also: ["K"] } },
        { id: '20', w: 1, h: 1, x: 10, y: 1, key: { code: "l", also: ["L"] } },
        { id: '21', w: 1, h: 1, x: 11, y: 1, key: { code: ";", also: [":"] } },
        { id: '22', w: 1, h: 1, x: 12, y: 1, key: { code: "'", also: ['"'] } },

        // Row 2
        { id: '23', w: 1, h: 1, x: 0, y: 2, key: { code: "shift", also: [] } },
        { id: '24', w: 1, h: 1, x: 1, y: 2, key: { code: "z", also: ["Z"] } },
        { id: '25', w: 1, h: 1, x: 2, y: 2, key: { code: "x", also: ["X"] } },
        { id: '26', w: 1, h: 1, x: 3, y: 2, key: { code: "c", also: ["C"] } },
        { id: '27', w: 1, h: 1, x: 4, y: 2, key: { code: "v", also: ["V"] } },
        { id: '28', w: 1, h: 1, x: 5, y: 2, key: { code: "b", also: ["B"] } },
        { id: '29', w: 1, h: 1, x: 7, y: 2, key: { code: "n", also: ["N"] } },
        { id: '30', w: 1, h: 1, x: 8, y: 2, key: { code: "m", also: ["M"] } },
        { id: '31', w: 1, h: 1, x: 9, y: 2, key: { code: ",", also: ["<"] } },
        { id: '32', w: 1, h: 1, x: 10, y: 2, key: { code: ".", also: [">"] } },
        { id: '33', w: 1, h: 1, x: 11, y: 2, key: { code: "/", also: ["?"] } },
        { id: '34', w: 1, h: 1, x: 12, y: 2, key: { code: "shift", also: [] } },

        // Row 3
        { id: '35', w: 1, h: 1, x: 2.25, y: 3.25, key: { code: "L1", also: [] } },
        { id: '36', w: 1, h: 1, x: 3.25, y: 3.25, key: { code: "ctrl", also: ["Ctrl"] } },
        { id: '37', w: 1, h: 1, x: 4.25, y: 3.25, key: { code: "Enter", also: ["L2"] } },

        // Row 4
        { id: '38', w: 1, h: 1, x: 5.75, y: 3.25, key: { code: "Leader", also: [] } },
        { id: '39', w: 1, h: 1, x: 6.75, y: 3.25, key: { code: "Space", also: ["L1"] } },
        { id: '40', w: 1, h: 1, x: 7.75, y: 3.25, key: { code: "NO", also: [] } },
    ]
}
